from .get_file_memory import *
from .modify_ppt_file import *
from .upload_ppt_file import *
#from .merge_ppt import *
from .delete_functions import *
from .insert_excel_ppt import *
from .include_data_json import *
from .include_images import *
from .include_gantt_chart import *